// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMbAPN3qm1DwflYE4uhkD0ORgvMqX2Elk',
    appId: '1:504217658511:web:7d31f13c1ef44693eabcfa',
    messagingSenderId: '504217658511',
    projectId: 'ucsbentoreceita',
    authDomain: 'ucsbentoreceita.firebaseapp.com',
    storageBucket: 'ucsbentoreceita.firebasestorage.app',
    measurementId: 'G-Z7ZCKZVFXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATGBCudAtC8QoPI0CWyqhXiT3203zNTQs',
    appId: '1:504217658511:android:7ae86fd1f4fb50b9eabcfa',
    messagingSenderId: '504217658511',
    projectId: 'ucsbentoreceita',
    storageBucket: 'ucsbentoreceita.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUYTqAl0tVTdMoh-m2FNAjH2idDJ6E3N4',
    appId: '1:504217658511:ios:69f914769a146795eabcfa',
    messagingSenderId: '504217658511',
    projectId: 'ucsbentoreceita',
    storageBucket: 'ucsbentoreceita.firebasestorage.app',
    iosBundleId: 'com.example.receitas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUYTqAl0tVTdMoh-m2FNAjH2idDJ6E3N4',
    appId: '1:504217658511:ios:69f914769a146795eabcfa',
    messagingSenderId: '504217658511',
    projectId: 'ucsbentoreceita',
    storageBucket: 'ucsbentoreceita.firebasestorage.app',
    iosBundleId: 'com.example.receitas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMbAPN3qm1DwflYE4uhkD0ORgvMqX2Elk',
    appId: '1:504217658511:web:10d9f50b49d56c5feabcfa',
    messagingSenderId: '504217658511',
    projectId: 'ucsbentoreceita',
    authDomain: 'ucsbentoreceita.firebaseapp.com',
    storageBucket: 'ucsbentoreceita.firebasestorage.app',
    measurementId: 'G-526R59Q0WN',
  );
}
